### ISSUE TITLE
Execute call causes Nap to hang.

### ISSUE THREAD

**Issue by agemoets** [mandest/Nap#4]
During a Post to a locally available service, Nap hangs. A cursory investigation indicates that the .Result call is causing the hang in the async call.

_napClient = new NapClient("http://localhost/");

_napClient.Post("/register")
.IncludeBody(entry)
.Execute<Entry>();

**Comment by mandest** [comment]
This should no longer be occurring.  This issue is relatively well-known for Web & Desktop applications, although console applications do not exhibit it's behavior - namely, only allowing one thread to be alive in the current synchronization context at a time.

Regardless, added code to be defensive about this behavior.  As with most async libraries, I'd recommend going async all the way down, but `Execute()` should no longer hang.
